### ISSUE TITLE
image with text embedded within article in confusing way (by blogging platform Ghost)

### ISSUE THREAD

**Issue by castedo** [front-matter/legacy.rogue-scholar#50]
The general issue here is images that contain textual content can be confused with the actual text content of a scholarly blog post. I see this as a deeper issue of aesthetics vs function, which in turn is part of an even deeper issue of the priorities of blog posters vs priorities of scholarly writers. Blog posts tend to optimize for aesthetic: be pretty. Whereas scholarly articles, say on PubMed Central optimize for function: communicate the facts clearly, be unambiguous, even if less visually appealing.

The webpage

https://blog.front-matter.io/posts/improved-pdf-formatted-rogue-scholar-blog-posts/

is an example. The image

https://blog.front-matter.io/content/images/2024/01/Bildschirmfoto-2024-01-12-um-16.53.20.png

shows up at the start of the blog post but is confusing. Is Chris Hunter the author of the blog post? Was the blog post published on Jan 10, 2024? No, that text is from the image and the author and pub date are in the left side bar. But that's not the first impression visiting the web page, especially if one is in the mind set of reading something with the layout of a scholarly article.

Similar confusion can happen with other types of images with text in other contexts.

Should the author be responsible for tweaking the images to have a border? Should authors rely on the rendering of an article having a nice clean minimalist lack of a border, or a say a white background?

My thought is that author should not rely on assumptions about how the article images will look nice within an article that is rendered on another website. My thought is the website doing the rendering should add a big clear border around the images similar to what one sees on PubMed Central. It doesn't matter that it looks uglier. It's scholarly so it should put the function of communicating facts over aesthetics.

**Comment by mfenner** [comment]
@castedo good points. And as you said, this is more a general issue than a specific bug. Let me think more about it. As I understand it, this is primarily about the Ghost theme the Front Matter blog uses, and how images are rendered.

**Comment by mfenner** [comment]
Closing this as this is a valid point, but this will not be addressed for the time being.
