### ISSUE TITLE
Could Rogue Scholar support WordPress-based publications?

### ISSUE THREAD

**Issue by mdingemanse** [front-matter/legacy.rogue-scholar#54]
Hi there, just found out about Rogue Scholar by searching for how to generate DOIs for WordPress posts. If creating an issue is not a good way to ask this question I'll be happy to close it if you direct me where to go. 

The question. I was looking at an interesting new scholar-led journal in my field that's been implemented in WordPress. I wanted to recommend them to use DOIs but first wanted to check out whether there's actually a reasonably easy way to do that. So: could Rogue Scholar help out here?

**Comment by mfenner** [comment]
DOI generation with Wordpress is relatively straightforward, as all the required metadata are already in Wordpress. 40% of the Rogue Scholar blogs use Wordpress and in 2023 I have registered 1000s of DOIs.

Rogue Scholar is a platform for science blogs so for journals we need to do something else. Contact me if you are interested.

**Comment by mdingemanse** [comment]
Thanks for helping out, Martin — closing this issue as I know where to go and what to do
